server:
  port: 8080
spring:
  application:
    name: reggie_take_out
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/reggie?characterEncoding=utf-8
    username: root
    password: admin
  resources:
    static-locations: classpath:/backend/
  mvc:
    static-path-pattern: classpath:/backend/
  redis:
    port: 6379
    host: 127.0.0.1
    database: 0
#    password: 123456
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: assign_id
reggie:
  path: C:\Users\Nikoo\Desktop\LinuxLocal\